web/src/Presentation/Nop.Web/Areas/Admin/Controllers/ReturnRequestController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core.Domain.Orders;
using Nop.Services.Catalog;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Infrastructure.Mapper.Extensions;
using Nop.Web.Areas.Admin.Models.Orders;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers;

public partial class ReturnRequestController : BaseAdminController
{
    #region Fields

    protected readonly ICustomerActivityService _customerActivityService;
    protected readonly ILocalizationService _localizationService;
    protected readonly ILocalizedEntityService _localizedEntityService;
    protected readonly INotificationService _notificationService;
    protected readonly IOrderService _orderService;
    protected readonly IProductService _productService;
    protected readonly IPermissionService _permissionService;
    protected readonly IReturnRequestModelFactory _returnRequestModelFactory;
    protected readonly IReturnRequestService _returnRequestService;
    protected readonly IWorkflowMessageService _workflowMessageService;

    #endregion Fields

    #region Ctor

    public ReturnRequestController(ICustomerActivityService customerActivityService,
        ILocalizationService localizationService,
        ILocalizedEntityService localizedEntityService,
        INotificationService notificationService,
        IOrderService orderService,
        IProductService productService,
        IPermissionService permissionService,
        IReturnRequestModelFactory returnRequestModelFactory,
        IReturnRequestService returnRequestService,
        IWorkflowMessageService workflowMessageService)
    {
        _customerActivityService = customerActivityService;
        _localizationService = localizationService;
        _localizedEntityService = localizedEntityService;
        _notificationService = notificationService;
        _orderService = orderService;
        _productService = productService;
        _permissionService = permissionService;
        _returnRequestModelFactory = returnRequestModelFactory;
        _returnRequestService = returnRequestService;
        _workflowMessageService = workflowMessageService;
    }

    #endregion

    #region Utilities

    protected virtual async Task UpdateLocalesAsync(ReturnRequestReason rrr, ReturnRequestReasonModel model)
    {
        foreach (var localized in model.Locales)
        {
            await _localizedEntityService.SaveLocalizedValueAsync(rrr,
                x => x.Name,
                localized.Name,
                localized.LanguageId);
        }
    }

    protected virtual async Task UpdateLocalesAsync(ReturnRequestAction rra, ReturnRequestActionModel model)
    {
        foreach (var localized in model.Locales)
        {
            await _localizedEntityService.SaveLocalizedValueAsync(rra,
                x => x.Name,
                localized.Name,
                localized.LanguageId);
        }
    }

    #endregion

    #region Methods

    public virtual IActionResult Index()
    {
        return RedirectToAction("List");
    }

    public virtual async Task<IActionResult> List()
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageReturnRequests))
            return AccessDeniedView();

        //prepare model
        var model = await _returnRequestModelFactory.PrepareReturnRequestSearchModelAsync(new ReturnRequestSearchModel());

        return View(model);
    }

    [HttpPost]
    public virtual async Task<IActionResult> List(ReturnRequestSearchModel searchModel)
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageReturnRequests))
            return await AccessDeniedDataTablesJson();

        //prepare model
        var model = await _returnRequestModelFactory.PrepareReturnRequestListModelAsync(searchModel);

        return Json(model);
    }

    public virtual async Task<IActionResult> Edit(int id)
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageReturnRequests))
            return AccessDeniedView();

        //try to get a return request with the specified id
        var returnRequest = await _returnRequestService.GetReturnRequestByIdAsync(id);
        if (returnRequest == null)
            return RedirectToAction("List");

        //prepare model
        var model = await _returnRequestModelFactory.PrepareReturnRequestModelAsync(null, returnRequest);

        return View(model);
    }

    [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
    [FormValueRequired("save", "save-continue")]
    public virtual async Task<IActionResult> Edit(ReturnRequestModel model, bool continueEditing)
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageReturnRequests))
            return AccessDeniedView();

        //try to get a return request with the specified id
        var returnRequest = await _returnRequestService.GetReturnRequestByIdAsync(model.Id);
        if (returnRequest == null)
            return RedirectToAction("List");

        if (ModelState.IsValid)
        {
            var quantityToReturn = model.ReturnedQuantity - returnRequest.ReturnedQuantity;
            if (quantityToReturn < 0)
                _notificationService.ErrorNotification(string.Format(await _localizationService.GetResourceAsync("Admin.ReturnRequests.Fields.ReturnedQuantity.CannotBeLessThanQuantityAlreadyReturned"), returnRequest.ReturnedQuantity));
            else
            {
                if (quantityToReturn > 0)
                {
                    var orderItem = await _orderService.GetOrderItemByIdAsync(returnRequest.OrderItemId);
                    if (orderItem != null)
                    {
                        var product = await _productService.GetProductByIdAsync(orderItem.ProductId);
                        if (product != null)
                        {
                            var productStockChangedMessage = string.Format(await _localizationService.GetResourceAsync("Admin.ReturnRequests.QuantityReturnedToStock"), quantityToReturn);

                            await _productService.AdjustInventoryAsync(product, quantityToReturn, orderItem.AttributesXml, productStockChangedMessage);

                            _notificationService.SuccessNotification(productStockChangedMessage);
                        }
                    }
                }

                returnRequest = model.ToEntity(returnRequest);
                returnRequest.UpdatedOnUtc = DateTime.UtcNow;

                await _returnRequestService.UpdateReturnRequestAsync(returnRequest);

                //activity log
                await _customerActivityService.InsertActivityAsync("EditReturnRequest",
                    string.Format(await _localizationService.GetResourceAsync("ActivityLog.EditReturnRequest"), returnRequest.Id), returnRequest);

                _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.ReturnRequests.Updated"));

                return continueEditing ? RedirectToAction("Edit", new { id = returnRequest.Id }) : RedirectToAction("List");
            }
        }

        //prepare model
        model = await _returnRequestModelFactory.PrepareReturnRequestModelAsync(model, returnRequest, true);

        //if we got this far, something failed, redisplay form
        return View(model);
    }

    [HttpPost, ActionName("Edit")]
    [FormValueRequired("notify-customer")]
    public virtual async Task<IActionResult> NotifyCustomer(ReturnRequestModel model)
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageReturnRequests))
            return AccessDeniedView();

        //try to get a return request with the specified id
        var returnRequest = await _returnRequestService.GetReturnRequestByIdAsync(model.Id);
        if (returnRequest == null)
            return RedirectToAction("List");

        var orderItem = await _orderService.GetOrderItemByIdAsync(returnRequest.OrderItemId);
        if (orderItem is null)
        {
            _notificationService.ErrorNotification(await _localizationService.GetResourceAsync("Admin.ReturnRequests.OrderItemDeleted"));
            return RedirectToAction("Edit", new { id = returnRequest.Id });
        }

        var order = await _orderService.GetOrderByIdAsync(orderItem.OrderId);

        var queuedEmailIds = await _workflowMessageService.SendReturnRequestStatusChangedCustomerNotificationAsync(returnRequest, orderItem, order);
        if (queuedEmailIds.Any())
            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.ReturnRequests.Notified"));

        return RedirectToAction("Edit", new { id = returnRequest.Id });
    }

    [HttpPost]
    public virtual async Task<IActionResult> Delete(int id)
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageReturnRequests))
            return AccessDeniedView();

        //try to get a return request with the specified id
        var returnRequest = await _returnRequestService.GetReturnRequestByIdAsync(id);
        if (returnRequest == null)
            return RedirectToAction("List");

        await _returnRequestService.DeleteReturnRequestAsync(returnRequest);

        //activity log
        await _customerActivityService.InsertActivityAsync("DeleteReturnRequest",
            string.Format(await _localizationService.GetResourceAsync("ActivityLog.DeleteReturnRequest"), returnRequest.Id), returnRequest);

        _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.ReturnRequests.Deleted"));

        return RedirectToAction("List");
    }

    #region Return request reasons

web/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/Edit.cshtml
@model ReturnRequestModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.ReturnRequests.EditReturnRequestDetails").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Return requests");
}

<form asp-controller="ReturnRequest" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.ReturnRequests.EditReturnRequestDetails")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.ReturnRequests.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="notify-customer" class="btn bg-purple">
                <i class="fas fa-at"></i>
                @T("Admin.ReturnRequests.NotifyCustomer")
            </button>
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="returnrequest-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ReturnRequestDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="returnrequest-delete" />

web/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/List.cshtml
@model ReturnRequestSearchModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.ReturnRequests").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Return requests");
}

@{
    const string hideSearchBlockAttributeName = "ReturnRequestsPage.HideSearchBlock";
    var hideSearchBlock = await genericAttributeService.GetAttributeAsync<bool>(await workContext.GetCurrentCustomerAsync(), hideSearchBlockAttributeName);
}

<div class="content-header clearfix">
    <h1 class="float-left">
        @T("Admin.ReturnRequests")
    </h1>
    <div class="float-right">
        &nbsp;
        @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ReturnRequestListButtons, additionalData = Model })
    </div>
</div>
<section class="content">
    <div class="container-fluid">
    <div class="form-horizontal">
        <div class="cards-group">
            <div class="card card-default card-search">
                <div class="card-body">
                    <div class="row search-row @(!hideSearchBlock ? "opened" : "")" data-hideAttribute="@hideSearchBlockAttributeName">
                        <div class="search-text">@T("Admin.Common.Search")</div>
                        <div class="icon-search"><i class="fas fa-search" aria-hidden="true"></i></div>
                        <div class="icon-collapse"><i class="far fa-angle-@(!hideSearchBlock ? "up" : "down")" aria-hidden="true"></i></div>
                    </div>

                    <div class="search-body @(hideSearchBlock ? "closed" : "")">

                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="StartDate" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="StartDate" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="EndDate" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="EndDate" />
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="CustomNumber" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-editor asp-for="CustomNumber" />
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-4">
                                        <nop-label asp-for="ReturnRequestStatusId" />
                                    </div>
                                    <div class="col-md-8">
                                        <nop-select asp-for="ReturnRequestStatusId" asp-items="Model.ReturnRequestStatusList" />
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="text-center col-12">
                                <button type="button" id="search-returnrequests" class="btn btn-primary btn-search">
                                    <i class="fas fa-search"></i>
                                    @T("Admin.Common.Search")
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="card card-default">
                <div class="card-body">
                    <p>
                        @T("Admin.ReturnRequests.Description")
                        <nop-doc-reference asp-string-resource="@T("Admin.Documentation.Reference.ReturnRequests", Docs.ReturnRequests + Utm.OnAdmin)" asp-add-wrapper="false"/>
                    </p>
                    @await Html.PartialAsync("Table", new DataTablesModel
                    {
                        Name = "returnrequests-grid",
                        UrlRead = new DataUrl("List", "ReturnRequest", null),
                        SearchButtonId = "search-returnrequests",
                        Length = Model.PageSize,
                        LengthMenu = Model.AvailablePageSizes,
                        Filters = new List<FilterParameter>
                        {
                            new FilterParameter(nameof(Model.StartDate), typeof(DateTime?)),
                            new FilterParameter(nameof(Model.EndDate), typeof(DateTime?)),
                            new FilterParameter(nameof(Model.CustomNumber)),
                            new FilterParameter(nameof(Model.ReturnRequestStatusId))
                        },
                        ColumnCollection = new List<ColumnProperty>
                        {
                            new ColumnProperty(nameof(ReturnRequestModel.CustomNumber))
                            {
                                Title = T("Admin.ReturnRequests.Fields.CustomNumber").Text,
                                Width = "100"
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.ProductName))
                            {
                                Title = T("Admin.ReturnRequests.Fields.Product").Text,
                                Width = "350",
                                Render = new RenderCustom("renderColumnProductName")
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.Quantity))
                            {
                                Title = T("Admin.ReturnRequests.Fields.Quantity").Text,
                                Width = "100"
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.ReturnedQuantity))
                            {
                                Title = T("Admin.ReturnRequests.Fields.ReturnedQuantity").Text,
                                Width = "100"
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.CustomerId))
                            {
                                Title = T("Admin.ReturnRequests.Fields.Customer").Text,
                                Width = "350",
                                Render = new RenderCustom("renderColumnCustomerInfo")
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.CustomOrderNumber))
                            {
                                Title = T("Admin.ReturnRequests.Fields.CustomOrderNumber").Text,
                                ClassName =  NopColumnClassDefaults.Button,
                                Width = "200",
                                Render = new RenderCustom("renderColumnOrderInfo")
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.ReturnRequestStatusStr))
                            {
                                Title = T("Admin.ReturnRequests.Fields.Status").Text,
                                Width = "200"
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.CreatedOn))
                            {
                                Title = T("Admin.ReturnRequests.Fields.CreatedOn").Text,
                                Width = "100",
                                Render = new RenderDate()
                            },
                            new ColumnProperty(nameof(ReturnRequestModel.Id))
                            {
                                Title = T("Admin.Common.Edit").Text,
                                Width = "100",
                                ClassName =  NopColumnClassDefaults.Button,
                                Render = new RenderButtonEdit(new DataUrl("Edit"))
                            }
                        }
                    })

                    <script asp-location="Footer">
                        function renderColumnProductName(data, type, row, meta) {
                            if (row.ProductId > 0) {
                                var textRenderer = $.fn.dataTable.render.text().display;
                                var productInfo = '<a href="@Url.Content("~/Admin/Product/Edit/")' + row.ProductId + '">' + textRenderer(row.ProductName) + '</a>';
                                var attributeInfo = '';
                                if (row.AttributeInfo && row.AttributeInfo.length > 0) {
                                    attributeInfo = '<div>' + row.AttributeInfo +'</div>';
                                }
                                return productInfo + attributeInfo;
                            } else {
                                return 'order item is deleted';
                            }
                        }

                        function renderColumnCustomerInfo(data, type, row, meta) {
                            var textRenderer = $.fn.dataTable.render.text().display;
                            return '<a href="@Url.Content("~/Admin/Customer/Edit/")' + row.CustomerId + '">' + textRenderer(row.CustomerInfo) + '</a>';
                        }

                        function renderColumnOrderInfo(data, type, row, meta) {
                            if (row.OrderId > 0) {
                                var textRenderer = $.fn.dataTable.render.text().display;
                                return '<a class="btn btn-default" href="@Url.Content("~/Admin/Order/Edit/")' + row.OrderId + '"><i class="far fa-eye"></i>' + textRenderer(row.CustomOrderNumber) + ' - @T("Admin.Common.View").Text</a>';
                            } else {
                                return 'order item is deleted';
                            }
                        }
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>
</section>

web/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestActionCreate.cshtml
@model ReturnRequestActionModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Configuration.Settings.Order.ReturnRequestActions.AddNew").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Order settings");
}

<form asp-controller="ReturnRequest" asp-action="ReturnRequestActionCreate" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestActions.AddNew")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestActionList">@T("Admin.Configuration.Settings.Order.ReturnRequestActions.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ReturnRequestActionDetailsButtons, additionalData = Model })
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestAction", Model)
            </div>
        </div>
    </section>
</form>

web/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestActionEdit.cshtml
@model ReturnRequestActionModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Configuration.Settings.Order.ReturnRequestActions.EditDetails").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Order settings");
}


<form asp-controller="ReturnRequest" asp-action="ReturnRequestActionEdit" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestActions.EditDetails") - @Model.Name
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestActionList">@T("Admin.Configuration.Settings.Order.ReturnRequestActions.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="returnrequestaction-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ReturnRequestActionDetailsButtons, additionalData = Model })
        </div>
    </div>

   <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestAction", Model)
            </div>
        </div>
   </section>
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="returnrequestaction-delete" asp-action="ReturnRequestActionDelete"/>

web/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestReasonCreate.cshtml
@model ReturnRequestReasonModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Configuration.Settings.Order.ReturnRequestReasons.AddNew").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Order settings");
}


<form asp-controller="ReturnRequest" asp-action="ReturnRequestReasonCreate" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestReasons.AddNew")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestReasonList">@T("Admin.Configuration.Settings.Order.ReturnRequestReasons.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ReturnRequestReasonDetailsButtons, additionalData = Model })
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestReason", Model)
            </div>
        </div>
    </section>
</form>

web/src/Presentation/Nop.Web/Areas/Admin/Views/ReturnRequest/ReturnRequestReasonEdit.cshtml
@model ReturnRequestReasonModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Configuration.Settings.Order.ReturnRequestReasons.EditDetails").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Order settings");
}

<form asp-controller="ReturnRequest" asp-action="ReturnRequestReasonEdit" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Configuration.Settings.Order.ReturnRequestReasons.EditDetails") - @Model.Name
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="ReturnRequestReasonList">@T("Admin.Configuration.Settings.Order.ReturnRequestReasons.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="returnrequestreason-delete" class="btn btn-danger">
                <i class="far fa-trash-alt"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ReturnRequestReasonDetailsButtons, additionalData = Model })
        </div>
    </div>

    <section class="content">
        <div class="container-fluid">
            <div class="form-horizontal">
                @await Html.PartialAsync("_CreateOrUpdate.ReturnRequestReason", Model)
            </div>
        </div>
    </section>
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="returnrequestreason-delete" asp-action="ReturnRequestReasonDelete"/>