web/src/Presentation/Nop.Web/Areas/Admin/Controllers/ProductReviewController.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Core.Events;
using Nop.Services.Catalog;
using Nop.Services.Customers;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Models.Catalog;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers;

public partial class ProductReviewController : BaseAdminController
{
    #region Fields

    protected readonly CatalogSettings _catalogSettings;
    protected readonly ICustomerActivityService _customerActivityService;
    protected readonly ICustomerService _customerService;
    protected readonly IEventPublisher _eventPublisher;
    protected readonly ILocalizationService _localizationService;
    protected readonly INotificationService _notificationService;
    protected readonly IPermissionService _permissionService;
    protected readonly IProductReviewModelFactory _productReviewModelFactory;
    protected readonly IProductService _productService;
    protected readonly IWorkContext _workContext;
    protected readonly IWorkflowMessageService _workflowMessageService;

    #endregion Fields

    #region Ctor

    public ProductReviewController(CatalogSettings catalogSettings,
        ICustomerActivityService customerActivityService,
        ICustomerService customerService,
        IEventPublisher eventPublisher,
        ILocalizationService localizationService,
        INotificationService notificationService,
        IPermissionService permissionService,
        IProductReviewModelFactory productReviewModelFactory,
        IProductService productService,
        IWorkContext workContext,
        IWorkflowMessageService workflowMessageService)
    {
        _catalogSettings = catalogSettings;
        _customerActivityService = customerActivityService;
        _customerService = customerService;
        _eventPublisher = eventPublisher;
        _localizationService = localizationService;
        _notificationService = notificationService;
        _permissionService = permissionService;
        _productReviewModelFactory = productReviewModelFactory;
        _productService = productService;
        _workContext = workContext;
        _workflowMessageService = workflowMessageService;
    }

    #endregion

    #region Methods

    public virtual IActionResult Index()
    {
        return RedirectToAction("List");
    }

    public virtual async Task<IActionResult> List()
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageProductReviews))
            return AccessDeniedView();

        //prepare model
        var model = await _productReviewModelFactory.PrepareProductReviewSearchModelAsync(new ProductReviewSearchModel());

        return View(model);
    }

    [HttpPost]
    public virtual async Task<IActionResult> List(ProductReviewSearchModel searchModel)
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageProductReviews))
            return await AccessDeniedDataTablesJson();

        //prepare model
        var model = await _productReviewModelFactory.PrepareProductReviewListModelAsync(searchModel);

        return Json(model);
    }

    public virtual async Task<IActionResult> Edit(int id)
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageProductReviews))
            return AccessDeniedView();

        //try to get a product review with the specified id
        var productReview = await _productService.GetProductReviewByIdAsync(id);
        if (productReview == null)
            return RedirectToAction("List");

        //a vendor should have access only to his products
        var currentVendor = await _workContext.GetCurrentVendorAsync();
        if (currentVendor != null && (await _productService.GetProductByIdAsync(productReview.ProductId)).VendorId != currentVendor.Id)
            return RedirectToAction("List");

        //prepare model
        var model = await _productReviewModelFactory.PrepareProductReviewModelAsync(null, productReview);

        return View(model);
    }

    [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
    public virtual async Task<IActionResult> Edit(ProductReviewModel model, bool continueEditing)
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageProductReviews))
            return AccessDeniedView();

        //try to get a product review with the specified id
        var productReview = await _productService.GetProductReviewByIdAsync(model.Id);
        if (productReview == null)
            return RedirectToAction("List");

        //a vendor should have access only to his products
        var currentVendor = await _workContext.GetCurrentVendorAsync();
        if (currentVendor != null && (await _productService.GetProductByIdAsync(productReview.ProductId)).VendorId != currentVendor.Id)
            return RedirectToAction("List");

        if (ModelState.IsValid)
        {
            var previousIsApproved = productReview.IsApproved;

            //vendor can edit "Reply text" only
            var isLoggedInAsVendor = currentVendor != null;
            if (!isLoggedInAsVendor)
            {
                productReview.Title = model.Title;
                productReview.ReviewText = model.ReviewText;
                productReview.IsApproved = model.IsApproved;
            }

            productReview.ReplyText = model.ReplyText;

            //notify customer about reply
            if (productReview.IsApproved && !string.IsNullOrEmpty(productReview.ReplyText)
                                         && _catalogSettings.NotifyCustomerAboutProductReviewReply && !productReview.CustomerNotifiedOfReply)
            {
                var customer = await _customerService.GetCustomerByIdAsync(productReview.CustomerId);
                var customerLanguageId = customer?.LanguageId ?? 0;

                var queuedEmailIds = await _workflowMessageService.SendProductReviewReplyCustomerNotificationMessageAsync(productReview, customerLanguageId);
                if (queuedEmailIds.Any())
                    productReview.CustomerNotifiedOfReply = true;
            }

            await _productService.UpdateProductReviewAsync(productReview);

            //activity log
            await _customerActivityService.InsertActivityAsync("EditProductReview",
                string.Format(await _localizationService.GetResourceAsync("ActivityLog.EditProductReview"), productReview.Id), productReview);

            //vendor can edit "Reply text" only
            if (!isLoggedInAsVendor)
            {
                var product = await _productService.GetProductByIdAsync(productReview.ProductId);
                //update product totals
                await _productService.UpdateProductReviewTotalsAsync(product);

                //raise event (only if it wasn't approved before and is approved now)
                if (!previousIsApproved && productReview.IsApproved)
                    await _eventPublisher.PublishAsync(new ProductReviewApprovedEvent(productReview));
            }

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Catalog.ProductReviews.Updated"));

            return continueEditing ? RedirectToAction("Edit", new { id = productReview.Id }) : RedirectToAction("List");
        }

        //prepare model
        model = await _productReviewModelFactory.PrepareProductReviewModelAsync(model, productReview, true);

        //if we got this far, something failed, redisplay form
        return View(model);
    }

    [HttpPost]
    public virtual async Task<IActionResult> Delete(int id)
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageProductReviews))
            return AccessDeniedView();

        //try to get a product review with the specified id
        var productReview = await _productService.GetProductReviewByIdAsync(id);
        if (productReview == null)
            return RedirectToAction("List");

        //a vendor does not have access to this functionality
        if (await _workContext.GetCurrentVendorAsync() != null)
            return RedirectToAction("List");

        await _productService.DeleteProductReviewAsync(productReview);

        //activity log
        await _customerActivityService.InsertActivityAsync("DeleteProductReview",
            string.Format(await _localizationService.GetResourceAsync("ActivityLog.DeleteProductReview"), productReview.Id), productReview);

        var product = await _productService.GetProductByIdAsync(productReview.ProductId);

        //update product totals
        await _productService.UpdateProductReviewTotalsAsync(product);

        _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Catalog.ProductReviews.Deleted"));

        return RedirectToAction("List");
    }

    [HttpPost]
    public virtual async Task<IActionResult> ApproveSelected(ICollection<int> selectedIds)
    {
        if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManageProductReviews))
            return AccessDeniedView();

        //a vendor does not have access to this functionality
        if (await _workContext.GetCurrentVendorAsync() != null)
            return RedirectToAction("List");

        if (selectedIds == null || !selectedIds.Any())
            return NoContent();

        //filter not approved reviews
        var productReviews = (await _productService.GetProductReviewsByIdsAsync(selectedIds.ToArray())).Where(review => !review.IsApproved);

        foreach (var productReview in productReviews)
        {
            productReview.IsApproved = true;
            await _productService.UpdateProductReviewAsync(productReview);

web/src/Presentation/Nop.Web/Areas/Admin/Views/ProductReview/Edit.cshtml
@model ProductReviewModel

@{
    //page title
    ViewBag.PageTitle = T("Admin.Catalog.ProductReviews.EditProductReviewDetails").Text;
    //active menu item (system name)
    NopHtml.SetActiveMenuItemSystemName("Product reviews");
}

<form asp-controller="ProductReview" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="float-left">
            @T("Admin.Catalog.ProductReviews.EditProductReviewDetails")
            <small>
                <i class="fas fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.Catalog.ProductReviews.BackToList")</a>
            </small>
        </h1>
        <div class="float-right">
            <button type="submit" name="save" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn btn-primary">
                <i class="far fa-save"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            @if (!Model.IsLoggedInAsVendor)
            {
                //this button is not visible to vendors
                <span id="productreview-delete" class="btn bg-red">
                    <i class="far fa-trash-alt"></i>
                    @T("Admin.Common.Delete")
                </span>
            }
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ProductReviewDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
@if (!Model.IsLoggedInAsVendor)
{
    //this button is not visible to vendors
    <nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="productreview-delete" />
}

web/src/Presentation/Nop.Web/Areas/Admin/Views/ProductReview/_CreateOrUpdate.cshtml
@model ProductReviewModel
@inject Nop.Services.Html.IHtmlFormatter htmlFormatter

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

<section class="content">
    <div class="container-fluid">
        <div class="form-horizontal">
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ProductReviewDetailsTop, additionalData = Model })
            <div class="cards-group">
                <div class="card card-default">
                    <div class="card-body">
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="ProductName" />
                            </div>
                            <div class="col-md-9">
                                <a asp-controller="Product" asp-action="Edit" asp-route-id="@Model.ProductId">@Model.ProductName</a>
                            </div>
                        </div>
                        @if (Model.ShowStoreName) 
                        { 
                            <div class="form-group row">
                                <div class="col-md-3">
                                    <nop-label asp-for="StoreName" />
                                </div>
                                <div class="col-md-9">
                                    <div class="form-text-row">@Model.StoreName</div>
                                </div>
                            </div>
                        }
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="CustomerInfo" />
                            </div>
                            <div class="col-md-9">
                                <a asp-controller="Customer" asp-action="Edit" asp-route-id="@Model.CustomerId">@Model.CustomerInfo</a>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="Title" />
                            </div>
                            <div class="col-md-9">
                                @if (Model.IsLoggedInAsVendor)
                                {
                                    <div class="form-text-row">@Model.Title</div>
                                }
                                else
                                {
                                    <nop-editor asp-for="Title" asp-required="true" />
                                    <span asp-validation-for="Title"></span>
                                }
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="ReviewText" />
                            </div>
                            <div class="col-md-9">
                                @if (Model.IsLoggedInAsVendor)
                                {
                                    @Html.Raw(htmlFormatter.FormatText(Model.ReviewText, false, true, false, false, false, false))
                                }
                                else
                                {
                                    <nop-textarea asp-for="ReviewText" asp-required="true" />
                                    <span asp-validation-for="ReviewText"></span>
                                }
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="ReplyText" />
                            </div>
                            <div class="col-md-9">
                                <nop-textarea asp-for="ReplyText" />
                                <span asp-validation-for="ReplyText"></span>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="Rating" />
                            </div>
                            <div class="col-md-9">
                                <div class="form-text-row">@Model.Rating</div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="IsApproved" />
                            </div>
                            <div class="col-md-9">
                                @if (Model.IsLoggedInAsVendor)
                                {
                                    <div class="form-text-row">
                                        @if (Model.IsApproved)
                                        {
                                            <i class="fas fa-check true-icon"></i>
                                        }
                                        else
                                        {
                                            <i class="fas fa-times false-icon"></i>
                                        }
                                    </div>
                                }
                                else
                                {
                                    <nop-editor asp-for="IsApproved" />
                                    <span asp-validation-for="IsApproved"></span>
                                }
                            </div>
                        </div>
                        <div class="form-group row">
                            <div class="col-md-3">
                                <nop-label asp-for="CreatedOn" />
                            </div>
                            <div class="col-md-9">
                                <div class="form-text-row">@Model.CreatedOn</div>
                            </div>
                        </div>
                        @if (Model.ProductReviewReviewTypeMappingSearchModel.IsAnyReviewTypes)
                        {
                            @await Html.PartialAsync("_ProductReviewReviewTypeMappingList", Model.ProductReviewReviewTypeMappingSearchModel)
                        }
                    </div>
                </div>
            </div>
            @await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ProductReviewDetailsBottom, additionalData = Model })
        </div>
    </div>
</section>

web/src/Presentation/Nop.Web/Areas/Admin/Views/ProductReview/_ProductReviewReviewTypeMappingList.cshtml
@model ProductReviewReviewTypeMappingSearchModel

@await Component.InvokeAsync(typeof(AdminWidgetViewComponent), new { widgetZone = AdminWidgetZones.ProductReviewDetailsTop, additionalData = Model })
<div class="card card-default">
    <div class="card-header">
        @T("Admin.Settings.ReviewType")
    </div>
    <div class="card-body">
        @await Html.PartialAsync("Table", new DataTablesModel
   {
       Name = "reviewext-grid",
       UrlRead = new DataUrl("ProductReviewReviewTypeMappingList", "ProductReview", new RouteValueDictionary { [nameof(Model.ProductReviewId)] = Model.ProductReviewId }),
       Length = Model.PageSize,
       LengthMenu = Model.AvailablePageSizes,
       ColumnCollection = new List<ColumnProperty>
            {
                new ColumnProperty(nameof(ProductReviewReviewTypeMappingModel.Name))
                {
                    Title = T("Admin.Catalog.AdditionalProductReviews.Fields.Name").Text,
                    Width = "300"
                },
                new ColumnProperty(nameof(ProductReviewReviewTypeMappingModel.Rating))
                {
                    Title = T("Admin.Catalog.AdditionalProductReviews.Fields.Rating").Text,
                    Width = "100"
                },
                new ColumnProperty(nameof(ProductReviewReviewTypeMappingModel.VisibleToAllCustomers))
                {
                    Title = T("Admin.Catalog.AdditionalProductReviews.Fields.VisibleToAllCustomers").Text,
                    Width = "100",
                    ClassName = NopColumnClassDefaults.CenterAll,
                    Render = new RenderBoolean()
                }
            }
   })
    </div>
</div>